spring.application.name=fooddeliveryapp
spring.datasource.url=jdbc:mysql://localhost:3306/fdapp
spring.datasource.username=root
spring.datasource.password=Dhanush@2204
spring.jpa.hibernate.ddl-auto=update
server.port=8080
